### ISSUE TITLE
Singleton not found!

### ISSUE THREAD

**Issue by BalintXHD** [syntaxerror247/godot-android-system-bar-color-changer#2]
It apparently doesn't find a singleton something... Not even the demo project works

**Comment by syntaxerror247** [comment]
Are you getting this error in editor?

**Comment by BalintXHD** [comment]
When I create the SystemBar.... node it spits the error into the console.

**Comment by syntaxerror247** [comment]
This just serves an an reminder that this plugin only works on android device.

You can ignore this, this is only a problem if it happens on android.

**Comment by BalintXHD** [comment]
I am developing from Windows to Android. It doesn't work if I try to change the color on the exported app on android. What do you mean??

edit: btw the demo project doesn't have the plugin pre installed

**Comment by syntaxerror247** [comment]
What version of the plugin are you using?

I have released a new version in GitHub but haven't updated it yet on AssetsLib.

**Comment by BalintXHD** [comment]
I used the version from AssetLib. I found my problem. It was that.

**Comment by syntaxerror247** [comment]
In previous versions you had to edit themes.xml file but it is now handled by the plugin.

@BalintXHD I think you haven't edited the themes.xml in previous versions. Right ?

**Comment by BalintXHD** [comment]
I just had the previous version from AssetLab. And I thought that the instructions from the ReadMe was for that version. Anyway I have the new version now. And the demo project from here now works.


But it still doesn't work in my project.

**Comment by syntaxerror247** [comment]
Did you enabled gradle build?

**Comment by BalintXHD** [comment]
Yep, immersive mode is off also.

Is there anywhere I can't call the functions?

edit: what color does it require? color object, rgb, hex?

**Comment by syntaxerror247** [comment]
Color object. Eg. Color.white
You can also directly give html color like "ffffff"

> Is there anywhere I can't call the functions?

No there is no such restrictions, you just need to have plugin node in your scenes

**Comment by BalintXHD** [comment]
Sooo I solved it.

I had to right click on the SystemBar.. node and enable the access as unique name
and from code I had to have %SystemBar.... instead of $SystemBar... .
